baseURL = "https://jrsue774-rgb.github.io/"
theme = "LoveIt"
themesDir = "../.."

title = "jrsue774-rgb"
defaultContentLanguage = "es"
languageCode = "es"
hasCJKLanguage = false
enableRobotsTXT = true
enableEmoji = true

[pagination]
  pagerSize = 10
  path = "page"

[params]
  defaultTheme = "auto"
  dateFormat = "2006-01-02"
  title = "jrsue774-rgb"
  description = "Bienvenido a mi blog de LINUX"
  images = ["/images/avatar.png"]

  [params.author]
    name = "jrsue774-rgb"
    email = ""
    link = ""

  [params.header]
    desktopMode = "fixed"
    mobileMode = "auto"
    [params.header.title]
      logo = ""
      name = "jrsue774-rgb"
      pre = ""
      post = ""
      typeit = false

  [params.footer]
    enable = true
    custom = "© 2026 jrsue774-rgb | Linux | Hugo | GitHub"
    hugo = true
    copyright = true
    author = true
    since = 2026

  [params.home]
    rss = 10
    [params.home.profile]
      enable = true
      gravatarEmail = ""
      avatarURL = "/images/avatar.png"
      title = ""
      subtitle = "Bienvenido a mi blog de LINUX"
      typeit = true
      social = true

  [params.social]
    GitHub = "jrsue774-rgb"
    RSS = true

  [params.search]
    enable = true
    type = "fuse"
    contentLength = 4000
    maxResultLength = 10
    snippetLength = 30
    highlightTag = "em"
    [params.search.fuse]
      minMatchCharLength = 2
      threshold = 0.3

  [params.section]
    paginate = 20
    dateFormat = "01-02"
    rss = 10

  [params.list]
    paginate = 20
    dateFormat = "01-02"
    rss = 10

  [params.page]
    lightgallery = true
    linkToMarkdown = false
    [params.page.toc]
      enable = true
      auto = false
    [params.page.code]
      copy = true
      maxShownLines = 50

[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
  [[menu.main]]
    weight = 2
    identifier = "acerca"
    name = "Acerca de mi"
    url = "/about/"
  [[menu.main]]
    weight = 3
    identifier = "linux"
    name = "Linux"
    url = "/categories/linux/"

[markup]
  [markup.highlight]
    codeFences = true
    lineNos = false
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]